CREATE TABLE
  source_types (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source_type VARCHAR(10),
    text VARCHAR(255),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  );